package uni.apps

import uni.*

/**
 * Regenerates the cross-language parity fixture in `test-data/hash-parity/` for
 * `uni`'s four file hashes and their Rust port (`rust/src/upath/hash.rs`).
 *
 * Consumed by two tests that must agree with each other:
 *   - uni.io.HashParitySuite      (Scala, src/test)
 *   - rust/tests/hash_parity.rs   (Rust)
 *
 * `md5`, `sha256` and `cksum` are pinned by published specifications, so the Rust
 * side checks those against RFC 1321, FIPS 180-4 and the POSIX utility as well --
 * this fixture is a second, independent check for them.
 *
 * `hash64` has no such anchor. It calls itself "based on the fast XXH3 algorithm" but
 * agrees with xxHash on nothing, so the Scala *is* its only specification and this
 * fixture is the whole of it.
 *
 * The `block-halves` pair guards a defect that was fixed: `processChunk` used to
 * advance 64 bytes while mixing only the first 32, so bytes 32-63 of every block never
 * reached the hash and the two 128-byte inputs below -- differing in 64 of their bytes
 * -- hashed identically. They must now differ.
 *
 * Sizes cluster around the boundaries that break hash implementations: 55/56/57 is
 * where MD5 and SHA-256 padding spills into an extra block, and 63/64/65 is the block
 * edge itself.
 *
 * Run ONLY when the reference is meant to move. Run:  sbt "runMain uni.apps.HashParityGen"
 */
object HashParityGen:
  def println(s: String = ""): Unit = print(s"$s\n")

  /** Deterministic filler; 251 is prime so the pattern does not align with 64. */
  def pattern(n: Int): Array[Byte] = Array.tabulate(n)(i => (i % 251).toByte)

  val cases: Seq[(String, Array[Byte])] =
    Seq(0, 1, 31, 32, 33, 55, 56, 57, 63, 64, 65, 127, 128, 129, 1000)
      .map(n => s"pattern-$n" -> pattern(n)) ++ Seq(
      "all-bytes"    -> Array.tabulate(256)(_.toByte),
      "zeros-64"     -> Array.fill(64)(0.toByte),
      "ones-64"      -> Array.fill(64)(0xff.toByte),
      "ascii"        -> "The quick brown fox jumps over the lazy dog".getBytes("UTF-8"),
      "utf8"         -> "naïve café — 日本語 — ¿qué?".getBytes("UTF-8"),
      "crlf"         -> "line one\r\nline two\r\n".getBytes("UTF-8"),
      // Two 128-byte inputs differing only in the halves `hash64` used to ignore.
      // Every hash, hash64 included, must now separate them.
      "block-halves-a" -> pattern(128),
      "block-halves-b" -> zeroHalves(pattern(128)),
    )

  /** Zeroes bytes 32-63 of every 64-byte block -- exactly what `hash64` used to skip. */
  def zeroHalves(b: Array[Byte]): Array[Byte] =
    Array.tabulate(b.length)(i => if (i % 64) >= 32 then 0.toByte else b(i))

  def main(args: Array[String]): Unit =
    val inputs = Paths.get("test-data/hash-parity/inputs")
    java.nio.file.Files.createDirectories(inputs)

    val lines = cases.map: (name, bytes) =>
      val file = Paths.get(s"test-data/hash-parity/inputs/$name.bin")
      java.nio.file.Files.write(file, bytes)
      val (crc, len) = file.cksum
      Seq(name, bytes.length, crc, len, file.hash64, file.md5, file.sha256).mkString("\t")

    val header = Seq(
      "# Cross-language hash parity reference. Generated by uni.apps.HashParityGen.",
      "# Do not hand-edit.",
      "# name<TAB>size<TAB>cksumCrc<TAB>cksumLen<TAB>hash64<TAB>md5<TAB>sha256",
      s"# cases: ${cases.length}",
    )
    val out = Paths.get("test-data/hash-parity/scala-reference.txt")
    out.writeLines(header ++ lines)
    println(s"wrote ${lines.length} cases -> ${out.posx}")
    FixtureGuard.warnIfIgnored(out.getParent)
