package uni.apps

import uni.*
import uni.data.*

/**
 * Regenerates the cross-language parity fixture in `test-data/mat-parity/` for the
 * reduction family of [[uni.data.Mat]] and its Rust port (`rust/src/udata/mat.rs`).
 *
 * Consumed by two tests that must agree with each other:
 *   - uni.data.MatParitySuite     (Scala, src/test)
 *   - rust/tests/mat_parity.rs    (Rust)
 *
 * Neither needs the other language installed, because both compare against the
 * committed reference rather than against each other.
 *
 * # What is actually being pinned
 *
 * Not "is the sum correct" — both languages would pass that with a naive fold. What is
 * pinned is the floating-point ASSOCIATION ORDER, because `Mat.sumD` chose speed over a
 * compensated sum and therefore has a specific, load-bearing shape:
 *
 *   - `sumRange` accumulates into 8 unrolled accumulators and combines them as
 *     `((s0+s1)+(s2+s3))+((s4+s5)+(s6+s7))`, then adds the tail one element at a time;
 *   - above `ParallelThreshold` (4096) the array is cut into
 *     `min(MaxSumChunks, n / 4096)` chunks — `MaxSumChunks` = 16, pinned to a CONSTANT
 *     rather than `availableProcessors` so the answer cannot vary with core count,
 *     container CPU limits or `-XX:ActiveProcessorCount` — each chunk summed by
 *     `sumRange`, partials then combined sequentially in index order.
 *
 * A Rust `iter().sum()` lands on a different last ulp, and every downstream statistic
 * (`mean`, and anything built on it) inherits that. Comparisons here are therefore on
 * raw IEEE-754 bit patterns, never on decimal text: a tolerance would wave through
 * exactly the drift this exists to catch.
 *
 * # Sizes
 *
 * The recorded sizes straddle BOTH thresholds, since each region exercises a different
 * chunk count and a different tail:
 *   - 0, 1, 7, 8, 9        — the unroll boundary, where the tail loop does all/none/some
 *   - 4095, 4096, 4097     — the sequential/parallel switch
 *   - 65535, 65536, 65537  — where `n / 4096` reaches `MaxSumChunks` and the cap starts
 *                            binding
 *   - 98304, 200000        — comfortably capped, and the size marketSim-scale work hits
 *
 * # Inputs
 *
 * Generated by [[uni.data.NumPyRNG]] rather than by a closed form, because the port is already
 * bit-identical there and `math.sin` is NOT: the JVM and Rust may round it differently
 * in the last ulp, which would break this fixture for a reason having nothing to do with
 * summation. `uniform` is one of the exact cases (only `randn` carries the `log1p`
 * caveat, so it is unused here).
 *
 * Magnitudes are deliberately mixed — alternating ~1e6 and ~1e-6 — so that reassociating
 * the sum actually MOVES the result. A uniform-magnitude corpus would let a wrong
 * association order pass by luck.
 *
 * Run ONLY when the reference is meant to move: regenerating rewrites the very values
 * the tests check. Review the diff before keeping it.
 *
 * Run:  sbt "runMain uni.apps.MatParityGen"
 */
object MatParityGen:
  def println(s: String = ""): Unit = print(s"$s\n")

  /** Sizes straddling the unroll boundary and both chunking thresholds. */
  val sizes: Vector[Int] =
    Vector(0, 1, 7, 8, 9, 4095, 4096, 4097, 65535, 65536, 65537, 98304, 200000)

  /**
   * 2-D shapes for the view/broadcast/axis cases, each scale in BOTH aspect ratios.
   *
   * The aspect ratio is not decoration. `Internal.create` materializes a "fragmented"
   * view into a contiguous copy, and its test compares the major stride against the row
   * count — so dropping a column from a 3×5 produces a copy (which then sums by `sumD`)
   * while the same operation on a 5×3 stays a view (which sums by a plain fold). A
   * fixture carrying only one orientation would pin only one of the two algorithms.
   *
   * Element counts again straddle both thresholds: 4095/4096 at the sequential/parallel
   * switch, 65536 where the `MaxSumChunks` cap starts binding, and 120000 above it.
   */
  val shapes: Vector[(Int, Int)] =
    Vector(
      (1, 1), (3, 5), (5, 3), (8, 9), (9, 8),
      (64, 64), (65, 63), (256, 256), (257, 256), (300, 400), (400, 300),
    )

  val Seed = 20260814L

  /** Raw IEEE-754 bits, so nothing is lost to decimal rendering. */
  def hex(d: Double): String = f"${java.lang.Double.doubleToRawLongBits(d)}%016x"

  def bits(d: Double): Long = java.lang.Double.doubleToRawLongBits(d)

  /** FNV-1a over 64-bit words, matching `NumPyRngParityGen` — one xor and one wrapping
   *  multiply per word, so it is trivially identical in both languages.
   *
   *  Used for the elementwise cases. An aggregate alone (a sum) could hide compensating
   *  per-element differences; a digest over every element cannot. That matters most for
   *  `exp`, where the JVM and Rust each round to within ~1 ulp but are not required to
   *  agree — this digest is what turns that question into a test result. */
  private val FnvOffset: Long = 0xcbf29ce484222325L
  private val FnvPrime: Long  = 0x100000001b3L

  def fnv(xs: Array[Double]): Long = fnvWords(xs.map(bits))

  def fnvWords(ws: Array[Long]): Long =
    var digest = FnvOffset
    var i      = 0
    while i < ws.length do
      digest = (digest ^ ws(i)) * FnvPrime
      i += 1
    digest

  /** Grid for [[quantize]]: 2^40, leaving ~40 bits of mantissa. */
  private val QuantumScale = 1099511627776.0

  /**
   * Snaps to a 2^-40 grid, as `NumPyRngParityGen` does for `randn`, and for the same
   * reason: `exp` is the one operation here that is NOT bit-identical across the port.
   *
   * MEASURED on this corpus (200,000 values). Rust's `f64::exp`, the platform C `exp`
   * and NumPy's `np.exp` are byte-identical to each other -- 0 differences. Java's
   * `Math.exp` differs from all three on 0.561% of values, never by more than 1 ulp.
   * `StrictMath.exp` (fdlibm) differs from `Math.exp` on 9.67%, 17x further away still.
   *
   * So the JVM is the outlier here, not Rust: `Math.exp` is a hand-written HotSpot
   * assembly intrinsic (from Intel's LIBM), not a libm call, so no platform C library
   * matches it -- and since this project treats NumPy as the fidelity oracle, the
   * divergence belongs to THIS side. Closing it means giving Scala a libm-backed exp
   * (FFM/Panama or JNI), which is a real change deliberately not taken yet. Until then,
   * pinning agreement to ~40 bits is the honest contract, and this fixture states it
   * rather than pretending to an exactness that does not exist.
   *
   * `floor(x * scale + 0.5)` rather than `rint`, because the two languages disagree on
   * exact halves; this form is identical in both.
   *
   * Residual risk, stated plainly: a one-ulp difference still changes the result when the
   * two values straddle a grid boundary — roughly 1 in 4000 per already-differing value.
   * That is a property of the COMMITTED numbers, not a coin flip at test time: these are
   * verified to agree once generated, and only a regeneration could introduce a straddle.
   */
  def quantize(d: Double): Long = Math.floor(d * QuantumScale + 0.5).toLong

  /** A coarser grid, 2^-32, for the `MatMathOps` rows. The 2^-40 grid assumes O(1)
   *  outputs: at |sinh(-5)| ≈ 74 it is only ~64 ulps wide, so a 1-ulp libm disagreement
   *  crosses a grid line with probability ~1/64 per differing element — and 4096 elements
   *  is enough. 32 significant bits still expose any wrong FORMULA, which is what those
   *  rows exist to pin; only a last-ulp libm difference is absorbed. */
  private val QuantumScale32 = 4294967296.0
  def quantize32(d: Double): Long = Math.floor(d * QuantumScale32 + 0.5).toLong

  /** 2^-24, for `softmax`/`logSoftmax` only: every element of a lane inherits the drift
   *  of a 400-term sum of `exp`s, so those rows carry several ulps of expected
   *  disagreement per element rather than one in a few hundred. */
  private val QuantumScale24 = 16777216.0
  def quantize24(d: Double): Long = Math.floor(d * QuantumScale24 + 0.5).toLong

  /** 2^-20, for the decompositions Scala takes from LAPACK (`svd`, `lstsq`, `pinv`,
   *  `cholesky`): the Rust side computes them with its own kernels (Jacobi SVD,
   *  Cholesky–Banachiewicz), so agreement is to the conditioning of the problem —
   *  ~1e-13 relative on these inputs — not to the ulp. 20 bits still expose a wrong
   *  formula, a wrong sign convention in `lstsq`, or a wrong rank threshold. */
  private val QuantumScale20 = 1048576.0
  def quantize20(d: Double): Long = Math.floor(d * QuantumScale20 + 0.5).toLong

  /**
   * The shared corpus: alternating large and tiny magnitudes so association order is
   * observable. Both languages build this from the same seed and take prefixes of it,
   * so the fixture need not carry 200k inputs.
   */
  def corpus(n: Int): Array[Double] =
    val rng = new NumPyRNG(Seed)
    Array.tabulate(n) { i =>
      if i % 2 == 0 then rng.uniform(-1e6, 1e6) else rng.uniform(-1e-6, 1e-6)
    }

  /**
   * A second corpus for the cases that must not overflow.
   *
   * `exp` of the main corpus would be `Infinity` almost everywhere (its values reach
   * 1e6), which would pin nothing. This range mirrors where marketSim actually applies
   * `exp`: log-equity below its running peak, i.e. values at or just below zero.
   */
  def corpusExp(n: Int): Array[Double] =
    val rng = new NumPyRNG(Seed + 1)
    Array.tabulate(n)(_ => rng.uniform(-5.0, 0.5))

  /** The recorded reductions, each a pure function of the prefix. */
  def cases(m: Mat[Double]): Vector[(String, Double)] = Vector(
    "sum"      -> m.sum,
    "mean"     -> m.mean,
    "abssum"   -> m.abs.sum,
    "sqsum"    -> m.power(2).sum,
    "sqmean"   -> m.power(2).mean,
    // cumsum is a sequential running total, so its last element pins a DIFFERENT
    // association order from `sum` on the same data -- a useful independent check that
    // the two were not conflated in either port.
    "cumlast"  -> (if m.isEmpty then 0.0 else m.cumsum.toArray.last),
  )

  /**
   * Cases over [[corpusExp]], recorded as raw Long words rather than Doubles.
   *
   * `expfnv` and `cummaxfnv` digest EVERY element, so a single-ulp disagreement anywhere
   * fails. `exp` is the one op here whose cross-language agreement was an open question
   * — Java's `Math.exp` and Rust's `f64::exp` are each permitted ~1 ulp of error and are
   * not required to agree — so this fixture is what settles it rather than an assumption.
   */
  def expCases(m: Mat[Double]): Vector[(String, Long)] =
    if m.isEmpty then
      Vector("expq" -> 0L, "min" -> 0L, "max" -> 0L, "cummaxfnv" -> 0L)
    else
      Vector(
        // QUANTIZED -- exp is the one op here that is not bit-identical; see quantize.
        "expq"      -> fnvWords(m.exp.toArray.map(quantize)),
        // Exact: no transcendental involved, so these stay bit-for-bit.
        "min"       -> bits(m.min),
        "max"       -> bits(m.max),
        "cummaxfnv" -> fnv(m.cummax(0).toArray),
      )

  /** A 2-D matrix over a prefix of the shared corpus, row-major. */
  def mat2d(all: Array[Double], rows: Int, cols: Int): Mat[Double] =
    Mat.create(java.util.Arrays.copyOfRange(all, 0, rows * cols), rows, cols)

  /**
   * The 2-D cases recorded as raw Doubles.
   *
   * Every one of these exists to pin something the *layout* decides rather than the
   * arithmetic. `tsum`/`tmean`/`tstd` run on a transposed view, which in Scala falls off
   * `fastD` and onto a plain sequential fold — a different association order from the
   * chunked `sumD` the same numbers get when contiguous. `slicesum` is the aspect-ratio
   * case: on a wide matrix the slice is materialized and lands back on `sumD`, on a tall
   * one it stays a view. A port that copied every view instead of carrying strides would
   * fail exactly here and nowhere else.
   */
  def cases2d(m: Mat[Double]): Vector[(String, Double)] =
    val t = m.T
    Vector(
      "tsum"     -> t.sum,
      "tmean"    -> t.mean,
      "tstd"     -> t.std,
      "std"      -> m.std,
      "var"      -> m.variance,
      "slicesum" -> m.slice(0 until m.rows, 1 until m.cols).sum,
      "normr"    -> m.ravel.norm,
    )

  /**
   * The 2-D cases recorded as raw Long words: FNV-1a digests over every element of a
   * result matrix, plus the two argmin/argmax positions flattened to `row * cols + col`.
   *
   * A digest rather than an aggregate because these produce whole matrices, and a sum of
   * a wrong result can still be right. Two pairs are load-bearing:
   *
   *   - `std0fnv` vs `tstd1fnv` cover the SAME lanes by the same formula, and are
   *     expected to differ. Scala's `std(axis)` takes each lane's mean with a plain fold
   *     when the matrix is contiguous, but by building the lane into a fresh matrix and
   *     calling `std` on it — hence `sumD` — when it is not. Recording both is what
   *     stops a port from unifying them.
   *   - `bcast0fnv`/`bcast1fnv` are the 1×N and N×1 broadcast shapes, the two Scala
   *     short-circuits in `fastBinOp`.
   */
  def wordCases2d(m: Mat[Double]): Vector[(String, Long)] =
    val t  = m.T
    val am = m.argmax
    val an = m.argmin
    Vector(
      "sum0fnv"   -> fnv(m.sum(0).toArray),
      "sum1fnv"   -> fnv(m.sum(1).toArray),
      "mean0fnv"  -> fnv(m.mean(0).toArray),
      "mean1fnv"  -> fnv(m.mean(1).toArray),
      "min0fnv"   -> fnv(m.min(0).toArray),
      "max1fnv"   -> fnv(m.max(1).toArray),
      "std0fnv"   -> fnv(m.std(0).toArray),
      "tstd1fnv"  -> fnv(t.std(1).toArray),
      "cum0fnv"   -> fnv(m.cumsum(0).toArray),
      "cum1fnv"   -> fnv(m.cumsum(1).toArray),
      "cmax0fnv"  -> fnv(m.cummax(0).toArray),
      "cmin1fnv"  -> fnv(m.cummin(1).toArray),
      "bcast0fnv" -> fnv((m - m.mean(0)).toArray),
      "bcast1fnv" -> fnv((m - m.mean(1)).toArray),
      "tfnv"      -> fnv(t.toArray),
      "slicefnv"  -> fnv(m.slice(0 until m.rows, 1 until m.cols).toArray),
      "divfnv"    -> fnv((m / (m.abs + 1.0)).toArray),
      "negfnv"    -> fnv((-m).toArray),
      "argmax"    -> (am._1.toLong * m.cols + am._2),
      "argmin"    -> (an._1.toLong * m.cols + an._2),
      // The pinned matmul: `m *@ m.T` (rows x rows) and `m.T *@ m` (cols x cols), through
      // `matmulPure` so the row does not depend on the JVM's BLAS mode. The second
      // operand is a transposed VIEW in both, so the strided read path is on the record.
      // Every cell is a sequential k-sum from 0.0; a BLAS or a blocked kernel lands
      // elsewhere in the last ulps at every size here except 1x1.
      "mmfnv"     -> fnv(m.matmulPure(t).toArray),
      "tmmfnv"    -> fnv(t.matmulPure(m).toArray),
    )

  /**
   * The `MatMathOps` family on a 2-D matrix over the bounded corpus (`corpusExp`, values
   * in [-5, 0.5]). Every one is a per-element formula, so what is pinned is the FORMULA
   * as the Scala spells it — `relu` as `Math.max` (NaN survives, -0.0 → +0.0), `log2` as
   * `ln x / ln 2`, `gelu`'s association, softmax's plain-fold sum after max-subtraction.
   *
   * Two encodings. The exact functions (`floor ceil trunc relu leakyRelu dropout`) go in
   * as raw bits and must agree bit for bit. The transcendental ones — everything routed
   * through `Math.sin`, `exp`, `tanh`, `log` — inherit the `exp` situation: HotSpot's
   * intrinsics and Rust's libm are each within an ulp and are not required to agree, so
   * those are pinned on a 2^-32 grid ([[quantize32]]; `softmax`/`logSoftmax` on 2^-24,
   * [[quantize24]]). Measured on this corpus, JVM vs Rust: `sin cos tan asin acos atan
   * atan2 log10 exp` differ on 0.1–21% of inputs by 1 ulp; `sinh cosh tanh log2 sigmoid`
   * by up to 2; `elu` by up to 64 and `gelu` by up to 3e5 ulps — the last two are the
   * FORMULA's conditioning (`1 + tanh(x)` near -1, `exp(x) - 1` near 0), and their
   * absolute error stays ~1e-16, which is why the grid is absolute. Domains keep every
   * output O(1) so no grid line is within an ulp: `tan` on `m/4` (no pole in
   * [-1.25, 0.125]), `arcsin`/`arccos`/`sinh`/`cosh` on `m/5`, the logs on `|m|+1`.
   */
  def mathCases(me: Mat[Double]): Vector[(String, Long)] =
    if me.isEmpty then Vector.empty
    else
      val pos   = me.abs + 1.0
      val small = me / 5.0
      val q     = (m: Mat[Double]) => fnvWords(m.toArray.map(quantize32))
      val q24   = (m: Mat[Double]) => fnvWords(m.toArray.map(quantize24))
      Vector(
        // exact
        "math.floor"      -> fnv(me.floor.toArray),
        "math.ceil"       -> fnv(me.ceil.toArray),
        "math.trunc"      -> fnv(me.trunc.toArray),
        "math.relu"       -> fnv(me.relu.toArray),
        "math.leakyRelu"  -> fnv(me.leakyRelu(0.01).toArray),
        "math.dropout"    -> fnv(me.dropout(0.3, training = true, seed = 20260816L).toArray),
        // quantized
        "math.sinq"       -> q(me.sin),
        "math.cosq"       -> q(me.cos),
        "math.tanq"       -> q((me / 4.0).tan),
        "math.arcsinq"    -> q(small.arcsin),
        "math.arccosq"    -> q(small.arccos),
        "math.arctanq"    -> q(me.arctan),
        "math.arctan2q"   -> q(me.arctan2(pos)),
        "math.sinhq"      -> q(small.sinh),
        "math.coshq"      -> q(small.cosh),
        "math.tanhq"      -> q(me.tanh),
        "math.log10q"     -> q(pos.log10),
        "math.log2q"      -> q(pos.log2),
        "math.sigmoidq"   -> q(me.sigmoid),
        "math.eluq"       -> q(me.elu(1.0)),
        "math.geluq"      -> q(me.gelu),
        "math.softmax0q"  -> q24(me.softmax(0)),
        "math.softmax1q"  -> q24(me.softmax(1)),
        "math.lsoftmax0q" -> q24(me.logSoftmax(0)),
        "math.lsoftmax1q" -> q24(me.logSoftmax(1)),
      )

  /**
   * Values the random corpus cannot reach, and which decide the ORDERING semantics of
   * `min`/`max`/`argmin`/`argmax`/`cummax`/`cummin`.
   *
   * These exist because the Rust port was wrong here and the 427-row fixture passed
   * anyway: `uniform(-1e6, 1e6)` produces no NaN and no signed zero, so a port that
   * compared with `<`/`>` looked correct. Scala compares through `Ordering[Double]`,
   * i.e. `java.lang.Double.compare`, under which:
   *
   *   - NaN ranks ABOVE every number, so `max` of a lane containing NaN is NaN;
   *   - `-0.0 < 0.0`, so `min(0.0, -0.0)` is `-0.0` and argmin moves off index 0.
   *
   * `negnan` is sharper still: it separates `java.lang.Double.compare` (which
   * canonicalises every NaN, so -NaN == +NaN and both outrank +Infinity) from Rust's
   * `f64::total_cmp` (IEEE totalOrder, which puts -NaN BELOW -Infinity). A port reaching
   * for `total_cmp` passes every other row here and fails this one.
   */
  val NegNaN: Double = java.lang.Double.longBitsToDouble(0xfff8000000000000L)

  val adversarial: Vector[(String, Array[Double])] = Vector(
    "nanmid"   -> Array(1.0, Double.NaN, -1.0, 2.0),
    "nanfirst" -> Array(Double.NaN, 1.0, -1.0),
    "nanonly"  -> Array(Double.NaN, Double.NaN),
    "negnan"   -> Array(NegNaN, 1.0, -1.0),
    "zeros"    -> Array(0.0, -0.0),
    "zerosrev" -> Array(-0.0, 0.0),
    "zerosmix" -> Array(1.0, -0.0, 0.0, -1.0),
    "infs"     -> Array(Double.PositiveInfinity, Double.NegativeInfinity, 0.0),
    "infnan"   -> Array(Double.PositiveInfinity, Double.NaN, Double.NegativeInfinity),
    "ties"     -> Array(3.0, 1.0, 1.0, 3.0),
  )

  /**
   * Bits, with every NaN collapsed to one pattern.
   *
   * IEEE-754 does not specify which NaN payload an arithmetic op propagates, so a raw
   * bit comparison of `sum` over a corpus containing NaN would pin a platform's choice
   * rather than the language's semantics. Canonicalising records the value CLASS, which
   * is the contract that actually holds. It is also exactly what
   * `Double.doubleToLongBits` does, so it matches the comparison being tested.
   */
  /**
   * The utility family on the main-corpus matrix `m`: `maximum`/`minimum` (which compare
   * with `Ordering[Double]`, not IEEE), `sign`, `round`, `nanToNum`, `tile`, `repeat`,
   * `scale`, the named broadcast helpers, `mapRows`, `hsplit`. All exact ports; raw bits.
   */
  def utilCases(m: Mat[Double]): Vector[(String, Long)] =
    val (rows, cols) = (m.rows, m.cols)
    val nanMat  = Mat.create(Array.fill(rows * cols)(Double.NaN), rows, cols)
    val withNaN = Mat.where(m.lt(0.0), nanMat, m)
    Vector(
      "ut.maxneg"  -> fnv(m.maximum(-m).toArray),
      "ut.minneg"  -> fnv(m.minimum(-m).toArray),
      "ut.maxs"    -> fnv(m.maximum(0.0).toArray),
      "ut.mins"    -> fnv(m.minimum(1e-6).toArray),
      "ut.sign"    -> fnv(m.sign.toArray),
      "ut.round2"  -> fnv(m.round(2).toArray),
      "ut.roundn3" -> fnv(m.round(-3).toArray),
      "ut.nan2num" -> fnv(withNaN.nanToNum(nan = -1.0).toArray),
      "ut.tile"    -> fnv(m.tile(2, 3).toArray),
      "ut.rep1"    -> fnv(m.repeat(2, axis = 1).toArray),
      "ut.rep0"    -> fnv(m.repeat(3, axis = 0).toArray),
      "ut.repflat" -> fnv(m.repeat(2).toArray),
      "ut.addrow"  -> fnv(m.addToEachRow(m.mean(0)).toArray),
      "ut.divcol"  -> fnv(m.divEachCol(m.abs.sum(1) + 1.0).toArray),
      "ut.maprows" -> fnv(m.mapRows(r => r - r.mean).toArray),
      "ut.mapcols" -> fnv(m.mapCols(c => c * 2.0).toArray),
    ) ++ (if rows >= 2 then Vector(
      "ut.scale"   -> fnv(m.scale().toArray),
      "ut.scalenc" -> fnv(m.scale(center = false).toArray),
    ) else Vector.empty) ++ (if cols >= 2 then Vector(
      "ut.hsplit"  -> fnv(m.hsplit(Array(1))(1).toArray),
    ) else Vector.empty)

  /**
   * `MatPandasOps` on the main-corpus matrix `m`: ordering under `Ordering[Double]`
   * (`sort argsort nlargest nsmallest unique valueCounts idxmin idxmax between`), the
   * differences (`diff shift pct_change`), order statistics (`percentile median
   * describe`), the rolling window and both `histogram` forms. Exact ports; raw bits.
   * Integer results (indices, counts) go in as their values.
   */
  def pandasCases(m: Mat[Double]): Vector[(String, Long)] =
    val (rows, cols) = (m.rows, m.cols)
    val ints = (a: Array[Int]) => fnvWords(a.map(_.toLong))
    val (uv, uc) = m.unique
    val (hc, he) = m.histogram(7)
    val edges = Seq(-1e6, -1.0, 0.0, 1.0, 1e6)
    val (hce, _) = m.histogram(edges)
    val r3 = m.rolling(3)
    Vector(
      "pd.sort"     -> fnv(m.sort().toArray),
      "pd.sort0"    -> fnv(m.sort(0).toArray),
      "pd.sort1"    -> fnv(m.sort(1).toArray),
      "pd.argsort"  -> ints(m.argsort().toArray),
      "pd.argsort0" -> ints(m.argsort(0).toArray),
      "pd.argsort1" -> ints(m.argsort(1).toArray),
      "pd.nlarge"   -> fnv(m.nlargest(5).toArray),
      "pd.nsmall"   -> fnv(m.nsmallest(5).toArray),
      "pd.between"  -> fnvMask(m.between(-1e5, 1e5)),
      "pd.uniqv"    -> fnv(uv),
      "pd.uniqc"    -> ints(uc),
      "pd.nuniq"    -> m.nunique.toLong,
      "pd.vcounts"  -> fnvWords(m.valueCounts.flatMap((v, c) => Array(bits(v), c.toLong))),
      "pd.idxmin0"  -> ints(m.idxmin(0).toArray),
      "pd.idxmax1"  -> ints(m.idxmax(1).toArray),
      "pd.shift0"   -> fnv(m.shift(1, Double.NaN, 0).toArray),
      "pd.shift1"   -> fnv(m.shift(-2, 0.0, 1).toArray),
      "pd.pct0"     -> fnv(m.pct_change(0).toArray),
      "pd.pct1"     -> fnv(m.pct_change(1).toArray),
      "pd.pctile"   -> bits(m.percentile(37.5)),
      "pd.median"   -> bits(m.median),
      "pd.pctile1"  -> fnv(m.percentile(90.0, 1).toArray),
      "pd.median0"  -> fnv(m.median(0).toArray),
      "pd.describe" -> fnv(m.describe._2.toArray),
      "pd.rmean"    -> fnv(r3.mean.toArray),
      "pd.rsum"     -> fnv(r3.sum.toArray),
      "pd.rmin"     -> fnv(r3.min.toArray),
      "pd.rmax"     -> fnv(r3.max.toArray),
      "pd.rstd"     -> fnv(r3.std.toArray),
      "pd.histc"    -> ints(hc),
      "pd.histe"    -> fnv(he),
      "pd.histec"   -> ints(hce),
    ) ++ (if m.size > 1 then Vector(
      "pd.diff"     -> fnv(m.diff.toArray),
    ) else Vector.empty) ++ (if rows > 1 then Vector(
      "pd.diff0"    -> fnv(m.diff(0).toArray),
    ) else Vector.empty) ++ (if cols > 1 then Vector(
      "pd.diff1"    -> fnv(m.diff(1).toArray),
    ) else Vector.empty)

  /**
   * `MatSignalOps` on the bounded corpus: `polyval`, `convolve`, `correlate` (all three
   * modes) as raw bits; `polyfit` (through `lstsq`) on the 2^-20 grid.
   */
  def signalCases(me: Mat[Double]): Vector[(String, Long)] =
    val (rows, cols) = (me.rows, me.cols)
    val a = me.slice(0 until 1, 0 until cols)          // 1 x cols
    val b = me.slice(0 until rows, 0 until 1)          // rows x 1
    Vector(
      "sg.polyval"  -> fnv(Mat.polyval(a, b).toArray),
      "sg.convf"    -> fnv(Mat.convolve(a, b, "full").toArray),
      "sg.convs"    -> fnv(Mat.convolve(a, b, "same").toArray),
      "sg.convv"    -> fnv(Mat.convolve(a, b, "valid").toArray),
      "sg.corrf"    -> fnv(Mat.correlate(a, b, "full").toArray),
      "sg.corrs"    -> fnv(Mat.correlate(a, b, "same").toArray),
      "sg.corrv"    -> fnv(Mat.correlate(a, b, "valid").toArray),
    ) ++ (if cols > 2 then Vector(
      "sg.polyfitq" -> fnvWords(Mat.polyfit(a, me.slice(rows - 1 until rows, 0 until cols), 2).toArray.map(quantize20)),
    ) else Vector.empty)

  /** Whether a shape gets the tolerance-pinned decomposition rows: small, or so far from
   *  square that a uniform random matrix is well conditioned. Near-square matrices past
   *  64 have condition numbers that push a 1e-15 kernel difference across the 2^-20 grid
   *  in a few of their thousands of cells; the pinned rows do not care. */
  def laTol(rows: Int, cols: Int): Boolean =
    rows.max(cols) <= 64 || (rows - cols).abs >= 100

  /**
   * The linear-algebra family on the bounded corpus (`corpusExp`, values in [-5, 0.5]);
   * the main corpus alternates 1e6 and 1e-6 magnitudes, which makes every matrix
   * hopelessly conditioned and every determinant overflow.
   *
   * Two encodings, as `mathCases`. The pure-JVM methods — `diagonal trace norm(ord)
   * determinant inverse solve qrDecomposition outer cross kron tril triu fillna cov
   * corrcoef` — are loops the Rust port reproduces operation for operation, so their
   * bits are pinned raw. The LAPACK-backed ones — `svd` (singular values), `lstsq`,
   * `matrixRank`, `pinv`, `cholesky`, `eig`/`eigenvalues` (sorted spectra) — are pinned
   * on the 2^-20 grid ([[quantize20]]) and only on the shapes [[laTol]] admits.
   */
  def linalgCases(me: Mat[Double]): Vector[(String, Long)] =
    val (rows, cols) = (me.rows, me.cols)
    val square = rows == cols
    val q20    = (xs: Array[Double]) => fnvWords(xs.map(quantize20))
    val nanMat = Mat.create(Array.fill(rows * cols)(Double.NaN), rows, cols)
    val withNaN = Mat.where(me.lt(-1.0), nanMat, me)
    val b      = me.abs.sum(1)                          // rows x 1
    val spd    = me.matmulPure(me.T) + MatD.eye(rows) * rows.toDouble
    val (qm, rm) = me.qrDecomposition
    val pinned = Vector(
      "la.diag"   -> fnv(me.diagonal),
      "la.trace"  -> bits(me.trace),
      "la.nfro"   -> bits(me.norm("fro")),
      "la.ninf"   -> bits(me.norm("inf")),
      "la.n1"     -> bits(me.norm("1")),
      "la.qrq"    -> fnv(qm.toArray),
      "la.qrr"    -> fnv(rm.toArray),
      "la.outer"  -> fnv(me.slice(0 until 1, 0 until cols).outer(me.slice(0 until rows, 0 until 1)).toArray),
      "la.kron"   -> fnv(me.kron(me.slice(0 until rows.min(2), 0 until cols.min(2))).toArray),
      "la.tril1"  -> fnv(me.tril(1).toArray),
      "la.triun1" -> fnv(me.triu(-1).toArray),
      "la.fillna" -> fnv(withNaN.fillna(7.0).toArray),
    ) ++ (if cols > 1 then Vector(
      "la.cov"    -> fnv(me.cov.toArray),
      "la.corr"   -> fnv(me.corrcoef.toArray),
    ) else Vector.empty) ++ (if rows >= 3 && cols >= 3 then Vector(
      "la.cross"  -> fnv(me.slice(0 until 1, 0 until 3).cross(me.slice(0 until 3, 0 until 1)).toArray),
    ) else Vector.empty) ++ (if square then Vector(
      "la.inv"    -> fnv(me.inverse.toArray),
      "la.solve"  -> fnv(me.solve(me.T).toArray),
    ) else Vector.empty) ++ (if square && rows <= 64 then Vector(
      "la.det"    -> bits(me.determinant),
    ) else Vector.empty)
    val tol = if !laTol(rows, cols) then Vector.empty else
      val (x, res, rank, sv) = me.lstsq(b)
      Vector(
        "la.svq"    -> q20(me.svd._2),
        "la.lstsqq" -> q20(x.toArray),
        "la.resq"   -> q20(res.toArray),
        "la.rank"   -> rank.toLong,
        "la.rank2"  -> me.matrixRank().toLong,
        "la.pinvq"  -> q20(me.pinv().toArray),
        "la.cholq"  -> q20(spd.cholesky.toArray),
      ) ++ (if rows <= 64 then Vector(
        // Symmetric spectrum, scaled by the trace so every eigenvalue is in (0, 1] and a
        // 1e-13 kernel difference cannot cross the grid.
        "la.symeigq" -> q20((spd / spd.trace).eigenvalues().sorted),
      ) else Vector.empty) ++ (if square then
        val (wr, wi, _) = me.eig
        val order = wr.indices.sortBy(i => (wr(i), wi(i)))
        Vector(
          "la.eigq"  -> q20(order.map(wr).toArray),
          "la.eigiq" -> q20(order.map(wi).toArray),
        )
      else Vector.empty)
    pinned ++ tol

  def canon(d: Double): Long =
    if d.isNaN then 0x7ff8000000000000L else bits(d)

  def fnvCanon(xs: Array[Double]): Long = fnvWords(xs.map(canon))

  /** The three orientations each adversarial array is recorded in. */
  def advShapes(arr: Array[Double]): Vector[(String, Mat[Double])] = Vector(
    "col"  -> Mat.create(arr.clone(), arr.length, 1),
    "row"  -> Mat.create(arr.clone(), 1, arr.length),
    "colT" -> Mat.create(arr.clone(), arr.length, 1).T,
  )

  /** A mask as an FNV digest, true as 1 and false as 0. */
  def fnvMask(mask: Mat[Boolean]): Long =
    fnvWords(mask.toArray.map(b => if b then 1L else 0L))

  /**
   * The mask family, over the same adversarial arrays.
   *
   * These pin the OPPOSITE ordering rule from the rest of this file. `min`/`max`/`argmax`
   * above use `Ordering[Double]` — `TotalOrdering`, NaN above every number, `-0.0` below
   * `0.0`. The mask family is IEEE, as NumPy's operators are: every comparison involving
   * NaN is false and `-0.0 == 0.0`. A port that routes masks through its ordering
   * comparator passes the rows above and fails these, which is the point of recording
   * both against the same inputs.
   *
   * The `colT` orientation matters as much as the values: a transposed view must compare
   * its own elements through the stride equation, not its parent's buffer in parent order.
   */
  def maskCases(m: Mat[Double]): Vector[(String, Long)] =
    val pos    = m.gt(0.0)
    val finite = m.isfinite
    val sel    = m(pos)
    Vector(
      "mask.gt0"       -> fnvMask(pos),
      "mask.lt0"       -> fnvMask(m.lt(0.0)),
      "mask.gte0"      -> fnvMask(m.gte(0.0)),
      "mask.lte0"      -> fnvMask(m.lte(0.0)),
      "mask.eq0"       -> fnvMask(m :== 0.0),
      "mask.ne0"       -> fnvMask(m :!= 0.0),
      // Every element compares false against NaN, and unequal to it.
      "mask.eqnan"     -> fnvMask(m :== Double.NaN),
      "mask.nenan"     -> fnvMask(m :!= Double.NaN),
      "mask.gtinf"     -> fnvMask(m.gt(Double.PositiveInfinity)),
      "mask.gteinf"    -> fnvMask(m.gte(Double.PositiveInfinity)),
      "mask.ltninf"    -> fnvMask(m.lt(Double.NegativeInfinity)),
      "mask.isnan"     -> fnvMask(m.isnan),
      "mask.isinf"     -> fnvMask(m.isinf),
      "mask.isfinite"  -> fnvMask(finite),
      "mask.and"       -> fnvMask(pos && finite),
      "mask.or"        -> fnvMask(pos || finite),
      "mask.not"       -> fnvMask(!pos),
      "mask.all"       -> (if pos.all then 1L else 0L),
      "mask.any"       -> (if pos.any then 1L else 0L),
      "mask.all0"      -> fnvMask(pos.all(0)),
      "mask.any0"      -> fnvMask(pos.any(0)),
      "mask.all1"      -> fnvMask(pos.all(1)),
      "mask.any1"      -> fnvMask(pos.any(1)),
      // The selection's SHAPE is recorded alongside its contents: an implementation that
      // returned n×1 instead of 1×n would otherwise pass on the digest alone.
      "mask.selfnv"    -> fnvCanon(sel.toArray),
      "mask.selshape"  -> (sel.rows.toLong * 1000 + sel.cols),
      "mask.wherefnv"  -> fnvCanon(Mat.where(pos, m, m * -1.0).toArray),
      "mask.wheresfnv" -> fnvCanon(Mat.where(pos, 1.0, -1.0).toArray),
    )

  def advCases(m: Mat[Double]): Vector[(String, Long)] =
    val an = m.argmin
    val ax = m.argmax
    Vector(
      "sum"      -> canon(m.sum),
      "min"      -> canon(m.min),
      "max"      -> canon(m.max),
      "argmin"   -> (an._1.toLong * m.cols + an._2),
      "argmax"   -> (ax._1.toLong * m.cols + ax._2),
      "cmax0fnv" -> fnvCanon(m.cummax(0).toArray),
      "cmax1fnv" -> fnvCanon(m.cummax(1).toArray),
      "cmin0fnv" -> fnvCanon(m.cummin(0).toArray),
      "cmin1fnv" -> fnvCanon(m.cummin(1).toArray),
      "min0fnv"  -> fnvCanon(m.min(0).toArray),
      "max1fnv"  -> fnvCanon(m.max(1).toArray),
    ) ++ maskCases(m)

  val header: String =
    """|# uni.data.Mat reduction parity reference (Scala <-> Rust).
       |# Regenerate with: sbt "runMain uni.apps.MatParityGen"
       |#
       |# Checked by uni.data.MatParitySuite and rust/tests/mat_parity.rs.
       |#
       |# Rows are:  <shape> <case> <hex>
       |# where <shape> is either a plain <n> (an n x 1 column over a prefix of the 1-D
       |# corpus) or <rows>x<cols> (a 2-D matrix over the same corpus, row-major), and
       |# <hex> is the raw 64-bit IEEE-754 pattern of the result, never decimal
       |# text -- what is pinned here is the floating-point ASSOCIATION ORDER of
       |# Mat.sumD (8 unrolled accumulators combined as ((s0+s1)+(s2+s3))+((s4+s5)+(s6+s7)),
       |# then min(MaxSumChunks=16, n/4096) chunks combined sequentially), and a
       |# tolerance would wave through exactly the drift this catches.
       |#
       |# INPUTS are not carried here; both sides rebuild them from NumPyRNG, which is
       |# already bit-identical across the port:
       |#
       |#   let rng = NumPyRNG(20260814)
       |#   x(i) = if i even then rng.uniform(-1e6, 1e6) else rng.uniform(-1e-6, 1e-6)
       |#
       |# drawn ONCE to the largest size, with every smaller size taking a prefix.
       |# Magnitudes alternate so that reassociating the sum actually moves the result;
       |# math.sin was rejected as a generator because the JVM and Rust may round it
       |# differently in the last ulp, which would fail this fixture for the wrong reason.
       |#
       |# Sizes straddle the 8-way unroll boundary and BOTH chunking thresholds (4096,
       |# and 65536 where the MaxSumChunks cap starts binding).
       |#
       |# The exp/min/max/cummax cases use a SECOND corpus, because exp of the first
       |# would be Infinity almost everywhere (its values reach 1e6) and would pin
       |# nothing. It mirrors where marketSim actually applies exp -- log-equity at or
       |# just below its running peak:
       |#
       |#   let rng2 = NumPyRNG(20260815)      // Seed + 1
       |#   xe(i) = rng2.uniform(-5.0, 0.5)
       |#
       |# expq and cummaxfnv are FNV-1a digests (offset cbf29ce484222325, prime
       |# 100000001b3) over EVERY element, so a per-element disagreement cannot hide
       |# inside an aggregate.
       |#
       |# exp is the ONE operation here that is not bit-identical across the port, and
       |# `expq` is therefore digested over values SNAPPED TO A 2^-40 GRID
       |# (floor(x * 2^40 + 0.5) -- not rint, which the two languages round differently
       |# on exact halves). Measured on this corpus: Java's Math.exp and Rust's f64::exp
       |# differ on 0.561% of 200,000 values, never by more than 1 ulp. Exact agreement
       |# is not available -- Math.exp is an unspecified HotSpot intrinsic, and the one
       |# portable alternative, StrictMath.exp (fdlibm), differs from Math.exp on 9.67%
       |# of the same corpus, 17x further away than Rust already is. min, max and
       |# cummax involve no transcendental and stay exact.
       |#
       |# The <rows>x<cols> rows pin the VIEW MODEL, which is the part of Mat a port is
       |# most likely to get subtly wrong. In Scala, transpose/slice/broadcastTo return
       |# zero-copy strided views, and the layout decides which summation algorithm runs:
       |# a contiguous matrix at offset 0 gets the chunked, 8-way unrolled sumD, anything
       |# else gets a plain sequential fold. So m.sum and m.T.sum are NOT required to
       |# agree -- and on this corpus they do not. A port that materialized every view
       |# into a fresh contiguous copy would silently take the fast path where Scala
       |# takes the slow one, and only these rows would notice.
       |#
       |# The aspect ratios are paired (3x5 and 5x3, 65x63 and 256x256, 300x400 and
       |# 400x300) because Internal.create materializes a "fragmented" view back into a
       |# contiguous copy, and its test compares the major stride against the row count.
       |# Dropping a column therefore copies on a wide matrix and stays a view on a tall
       |# one -- the same logical slice, two different summation algorithms.
       |#
       |# std0fnv and tstd1fnv reduce the SAME lanes by the same formula and are expected
       |# to DIFFER: std(axis) takes each lane's mean by a plain fold when the matrix is
       |# contiguous, and via sumD when it is not.
       |#
       |# The *fnv cases are FNV-1a digests over every element of a result matrix;
       |# argmin/argmax are positions flattened as row * cols + col.
       |#
       |# The adv/<name>/<orientation> rows pin ORDERING semantics, on values the random
       |# corpus cannot produce. They exist because the Rust port was wrong here while
       |# every other row passed: uniform(-1e6, 1e6) yields no NaN and no signed zero, so
       |# comparing with `<`/`>` looked correct. Scala compares through Ordering[Double],
       |# i.e. java.lang.Double.compare, under which NaN ranks ABOVE every number (so max
       |# of a lane containing NaN is NaN) and -0.0 < 0.0 (so min(0.0, -0.0) is -0.0 and
       |# argmin moves off index 0).
       |#
       |# `negnan` is the sharpest of them: it separates java.lang.Double.compare, which
       |# canonicalises every NaN so that -NaN == +NaN and both outrank +Infinity, from
       |# Rust's f64::total_cmp, which implements IEEE totalOrder and places -NaN BELOW
       |# -Infinity. A port reaching for total_cmp passes every other adversarial row and
       |# fails this one.
       |#
       |# Values in these rows are recorded with every NaN collapsed to 7ff8000000000000.
       |# IEEE does not specify which payload an arithmetic op propagates, so a raw bit
       |# comparison would pin a platform's choice rather than the language's semantics.
       |""".stripMargin

  def main(args: Array[String]): Unit =
    val root = sys.props.getOrElse("user.dir", ".")
    val dir  = s"$root/test-data/mat-parity"
    java.nio.file.Files.createDirectories(dir.asPath)

    val maxN   = sizes.max
    val all    = corpus(maxN)
    val allExp = corpusExp(maxN)

    val sb = StringBuilder()
    sb ++= header
    for n <- sizes.sorted do
      val m  = MatD(java.util.Arrays.copyOfRange(all, 0, n))
      val me = MatD(java.util.Arrays.copyOfRange(allExp, 0, n))
      for (label, value) <- cases(m) do
        sb ++= s"$n $label ${hex(value)}\n"
      for (label, word) <- expCases(me) do
        sb ++= f"$n $label $word%016x\n"
      println(s"  n=$n: ${cases(m).length + expCases(me).length} cases")

    for (rows, cols) <- shapes do
      val m  = mat2d(all, rows, cols)
      val me = mat2d(allExp, rows, cols)
      for (label, value) <- cases2d(m) do
        sb ++= s"${rows}x$cols $label ${hex(value)}\n"
      for (label, word) <- wordCases2d(m) do
        sb ++= f"${rows}x$cols $label $word%016x\n"
      for (label, word) <- mathCases(me) do
        sb ++= f"${rows}x$cols $label $word%016x\n"
      for (label, word) <- linalgCases(me) do
        sb ++= f"${rows}x$cols $label $word%016x\n"
      for (label, word) <- utilCases(m) do
        sb ++= f"${rows}x$cols $label $word%016x\n"
      for (label, word) <- pandasCases(m) do
        sb ++= f"${rows}x$cols $label $word%016x\n"
      for (label, word) <- signalCases(me) do
        sb ++= f"${rows}x$cols $label $word%016x\n"
      println(s"  ${rows}x$cols: ${cases2d(m).length + wordCases2d(m).length + mathCases(me).length + linalgCases(me).length + utilCases(m).length + pandasCases(m).length + signalCases(me).length} cases")

    for (name, arr) <- adversarial do
      for (orient, m) <- advShapes(arr) do
        for (label, word) <- advCases(m) do
          sb ++= f"adv/$name/$orient $label $word%016x\n"
      println(s"  adv/$name: ${advShapes(arr).length * advCases(advShapes(arr).head._2).length} cases")

    val out = s"$dir/scala-reference.txt"
    java.nio.file.Files.writeString(out.asPath, sb.toString)
    println(s"wrote $out")
    FixtureGuard.warnIfIgnored(dir.asPath)
