package uni.apps

import uni.*
import uni.data.*

/**
 * Regenerates the cross-language parity fixture in `test-data/mat-parity/` for the
 * reduction family of [[uni.data.Mat]] and its Rust port (`rust/src/udata/mat.rs`).
 *
 * Consumed by two tests that must agree with each other:
 *   - uni.data.MatParitySuite     (Scala, src/test)
 *   - rust/tests/mat_parity.rs    (Rust)
 *
 * Neither needs the other language installed, because both compare against the
 * committed reference rather than against each other.
 *
 * # What is actually being pinned
 *
 * Not "is the sum correct" — both languages would pass that with a naive fold. What is
 * pinned is the floating-point ASSOCIATION ORDER, because `Mat.sumD` chose speed over a
 * compensated sum and therefore has a specific, load-bearing shape:
 *
 *   - `sumRange` accumulates into 8 unrolled accumulators and combines them as
 *     `((s0+s1)+(s2+s3))+((s4+s5)+(s6+s7))`, then adds the tail one element at a time;
 *   - above `ParallelThreshold` (4096) the array is cut into
 *     `min(MaxSumChunks, n / 4096)` chunks — `MaxSumChunks` = 16, pinned to a CONSTANT
 *     rather than `availableProcessors` so the answer cannot vary with core count,
 *     container CPU limits or `-XX:ActiveProcessorCount` — each chunk summed by
 *     `sumRange`, partials then combined sequentially in index order.
 *
 * A Rust `iter().sum()` lands on a different last ulp, and every downstream statistic
 * (`mean`, and anything built on it) inherits that. Comparisons here are therefore on
 * raw IEEE-754 bit patterns, never on decimal text: a tolerance would wave through
 * exactly the drift this exists to catch.
 *
 * # Sizes
 *
 * The recorded sizes straddle BOTH thresholds, since each region exercises a different
 * chunk count and a different tail:
 *   - 0, 1, 7, 8, 9        — the unroll boundary, where the tail loop does all/none/some
 *   - 4095, 4096, 4097     — the sequential/parallel switch
 *   - 65535, 65536, 65537  — where `n / 4096` reaches `MaxSumChunks` and the cap starts
 *                            binding
 *   - 98304, 200000        — comfortably capped, and the size marketSim-scale work hits
 *
 * # Inputs
 *
 * Generated by [[NumPyRNG]] rather than by a closed form, because the port is already
 * bit-identical there and `math.sin` is NOT: the JVM and Rust may round it differently
 * in the last ulp, which would break this fixture for a reason having nothing to do with
 * summation. `uniform` is one of the exact cases (only `randn` carries the `log1p`
 * caveat, so it is unused here).
 *
 * Magnitudes are deliberately mixed — alternating ~1e6 and ~1e-6 — so that reassociating
 * the sum actually MOVES the result. A uniform-magnitude corpus would let a wrong
 * association order pass by luck.
 *
 * Run ONLY when the reference is meant to move: regenerating rewrites the very values
 * the tests check. Review the diff before keeping it.
 *
 * Run:  sbt "runMain uni.apps.MatParityGen"
 */
object MatParityGen:
  def println(s: String = ""): Unit = print(s"$s\n")

  /** Sizes straddling the unroll boundary and both chunking thresholds. */
  val sizes: Vector[Int] =
    Vector(0, 1, 7, 8, 9, 4095, 4096, 4097, 65535, 65536, 65537, 98304, 200000)

  val Seed = 20260814L

  /** Raw IEEE-754 bits, so nothing is lost to decimal rendering. */
  def hex(d: Double): String = f"${java.lang.Double.doubleToRawLongBits(d)}%016x"

  /**
   * The shared corpus: alternating large and tiny magnitudes so association order is
   * observable. Both languages build this from the same seed and take prefixes of it,
   * so the fixture need not carry 200k inputs.
   */
  def corpus(n: Int): Array[Double] =
    val rng = new NumPyRNG(Seed)
    Array.tabulate(n) { i =>
      if i % 2 == 0 then rng.uniform(-1e6, 1e6) else rng.uniform(-1e-6, 1e-6)
    }

  /** The recorded reductions, each a pure function of the prefix. */
  def cases(m: Mat[Double]): Vector[(String, Double)] = Vector(
    "sum"      -> m.sum,
    "mean"     -> m.mean,
    "abssum"   -> m.abs.sum,
    "sqsum"    -> m.power(2).sum,
    "sqmean"   -> m.power(2).mean,
    // cumsum is a sequential running total, so its last element pins a DIFFERENT
    // association order from `sum` on the same data -- a useful independent check that
    // the two were not conflated in either port.
    "cumlast"  -> (if m.isEmpty then 0.0 else m.cumsum.toArray.last),
  )

  val header: String =
    """|# uni.data.Mat reduction parity reference (Scala <-> Rust).
       |# Regenerate with: sbt "runMain uni.apps.MatParityGen"
       |#
       |# Checked by uni.data.MatParitySuite and rust/tests/mat_parity.rs.
       |#
       |# Rows are:  <n> <case> <hex>
       |# where <hex> is the raw 64-bit IEEE-754 pattern of the result, never decimal
       |# text -- what is pinned here is the floating-point ASSOCIATION ORDER of
       |# Mat.sumD (8 unrolled accumulators combined as ((s0+s1)+(s2+s3))+((s4+s5)+(s6+s7)),
       |# then min(MaxSumChunks=16, n/4096) chunks combined sequentially), and a
       |# tolerance would wave through exactly the drift this catches.
       |#
       |# INPUTS are not carried here; both sides rebuild them from NumPyRNG, which is
       |# already bit-identical across the port:
       |#
       |#   let rng = NumPyRNG(20260814)
       |#   x(i) = if i even then rng.uniform(-1e6, 1e6) else rng.uniform(-1e-6, 1e-6)
       |#
       |# drawn ONCE to the largest size, with every smaller size taking a prefix.
       |# Magnitudes alternate so that reassociating the sum actually moves the result;
       |# math.sin was rejected as a generator because the JVM and Rust may round it
       |# differently in the last ulp, which would fail this fixture for the wrong reason.
       |#
       |# Sizes straddle the 8-way unroll boundary and BOTH chunking thresholds (4096,
       |# and 65536 where the MaxSumChunks cap starts binding).
       |""".stripMargin

  def main(args: Array[String]): Unit =
    val root = sys.props.getOrElse("user.dir", ".")
    val dir  = s"$root/test-data/mat-parity"
    java.nio.file.Files.createDirectories(dir.asPath)

    val maxN = sizes.max
    val all  = corpus(maxN)

    val sb = StringBuilder()
    sb ++= header
    for n <- sizes.sorted do
      val m = MatD(java.util.Arrays.copyOfRange(all, 0, n))
      for (label, value) <- cases(m) do
        sb ++= s"$n $label ${hex(value)}\n"
      println(s"  n=$n: ${cases(m).length} cases")

    val out = s"$dir/scala-reference.txt"
    java.nio.file.Files.writeString(out.asPath, sb.toString)
    println(s"wrote $out")
    FixtureGuard.warnIfIgnored(dir.asPath)
