//! Checks the hand-rolled `Big` decimal against `test-data/big-parity/scala-reference.txt`
//! — `java.math.BigDecimal`'s own answers, generated by `uni.apps.BigParityGen`. Renderings
//! are compared, so scale survives as well as numeric value.

#![allow(
    clippy::expect_used,
    clippy::panic,
    reason = "a missing or malformed fixture should abort the test loudly"
)]

use t3prf::udata::Big;
use t3prf::udata::big::RoundingMode;

fn fixture_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../test-data/big-parity/scala-reference.txt")
}

/// `!nan` in an operand column means the sentinel itself.
fn read(s: &str) -> Big {
    if s == "!nan" { Big::nan() } else { Big::parse(s) }
}

fn render(b: &Big) -> String {
    if b.isNaN() { "!nan".to_owned() } else { b.toString() }
}

fn mode_of(name: &str) -> RoundingMode {
    match name {
        "UP" => RoundingMode::Up,
        "DOWN" => RoundingMode::Down,
        "CEILING" => RoundingMode::Ceiling,
        "FLOOR" => RoundingMode::Floor,
        "HALF_UP" => RoundingMode::HalfUp,
        "HALF_DOWN" => RoundingMode::HalfDown,
        "HALF_EVEN" => RoundingMode::HalfEven,
        other => panic!("unknown rounding mode {other}"),
    }
}

/// Java's `Double.toString`, for the `todouble` rows (the fixture records Scala's rendering
/// of the resulting double, not the double itself).
fn java_double_string(d: f64) -> String {
    if d.is_nan() {
        return "NaN".to_owned();
    }
    if d == 0.0 {
        return if d.is_sign_negative() { "-0.0".into() } else { "0.0".into() };
    }
    let sci = format!("{d:e}");
    let (mantissa, exp_str) = sci.split_once('e').unwrap_or((sci.as_str(), "0"));
    let exp: i64 = exp_str.parse().unwrap_or(0);
    let (sign, mantissa) = match mantissa.strip_prefix('-') {
        Some(m) => ("-", m),
        None => ("", mantissa),
    };
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    if (-3..7).contains(&exp) {
        let point = exp + 1;
        if point <= 0 {
            format!("{sign}0.{}{}", "0".repeat((-point) as usize), digits)
        } else if (point as usize) >= digits.len() {
            format!("{sign}{}{}.0", digits, "0".repeat(point as usize - digits.len()))
        } else {
            format!("{sign}{}.{}", &digits[..point as usize], &digits[point as usize..])
        }
    } else {
        let head = &digits[..1];
        let tail = if digits.len() > 1 { &digits[1..] } else { "0" };
        format!("{sign}{head}.{tail}E{exp}")
    }
}

#[test]
#[expect(clippy::too_many_lines, reason = "one row loop, one match arm per fixture op")]
fn every_fixture_row_reproduces() {
    let text =
        std::fs::read_to_string(fixture_path()).expect("missing fixture; run BigParityGen");
    let rows: Vec<&str> =
        text.lines().filter(|l| !l.is_empty() && !l.starts_with('#')).collect();
    assert!(rows.len() > 300, "suspiciously small fixture: {} rows", rows.len());

    let mut failures: Vec<String> = Vec::new();
    let mut check = |label: String, got: String, want: &str| {
        if got != want {
            failures.push(format!("{label}: got {got}, want {want}"));
        }
    };
    for row in &rows {
        let p: Vec<&str> = row.split('\t').collect();
        match p.as_slice() {
            ["parse", input, want] => check(format!("parse '{input}'"), render(&Big::parse(input)), want),
            ["parse", want] => check("parse ''".into(), render(&Big::parse("")), want),
            ["plain", input, want] => {
                check(format!("plain '{input}'"), Big::parse(input).toPlainString(), want);
            }
            [op @ ("add" | "sub" | "mul" | "div"), a, b, want] => {
                let (x, y) = (read(a), read(b));
                let got = match *op {
                    "add" => x.add(&y),
                    "sub" => x.sub(&y),
                    "mul" => x.mul(&y),
                    _ => x.div(&y),
                };
                check(format!("{op} {a} {b}"), render(&got), want);
            }
            ["cmp", a, b, want] => {
                check(format!("cmp {a} {b}"), read(a).compare(&read(b)).to_string(), want);
            }
            ["setscale", a, sc, mode, want] => {
                let scale: i32 = sc.parse().expect("scale");
                let got = read(a).setScale(scale, mode_of(mode));
                check(format!("setscale {a} {sc} {mode}"), render(&got), want);
            }
            ["neg", a, want] => check(format!("neg {a}"), render(&read(a).neg()), want),
            ["abs", a, want] => check(format!("abs {a}"), render(&read(a).abs()), want),
            ["sqrt", a, want] => check(format!("sqrt {a}"), render(&read(a).sqrt()), want),
            ["pow", a, e, want] => {
                let exp: i32 = e.parse().expect("exp");
                check(format!("pow {a} {e}"), render(&read(a).pow(exp)), want);
            }
            ["powf", a, e, want] => {
                let exp: f64 = e.parse().expect("exp");
                check(format!("powf {a} {e}"), render(&read(a).powf(exp)), want);
            }
            ["fromdouble", d, want] => {
                let v: f64 = d.parse().expect("double literal");
                check(format!("fromdouble {d}"), render(&Big::from_f64(v)), want);
            }
            ["todouble", a, want] => {
                check(format!("todouble {a}"), java_double_string(read(a).toDouble()), want);
            }
            ["toint", a, want] => check(format!("toint {a}"), read(a).toInt().to_string(), want),
            ["tolong", a, want] => check(format!("tolong {a}"), read(a).toLong().to_string(), want),
            // The loader rows are checked by `big_loaders.rs`, which needs the csv module.
            ["csvdim" | "csvcell", ..] => {}
            _ => check("row".into(), (*row).to_owned(), "a known op"),
        }
    }
    assert!(
        failures.is_empty(),
        "{} divergence(s):\n{}",
        failures.len(),
        failures.join("\n")
    );
}
